name = "promopopup"
client_id = "f25a308c93487fa414a0010181d3718a"
application_url = "https://promopopup.vercel.app"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = ["https://promopopup.vercel.app/auth/callback", "https://promopopup.vercel.app/auth/shopify/callback", "https://promopopup.vercel.app/api/auth/callback"]

[webhooks]
api_version = "2024-01"

[extensions.theme]
handle = "promopopup-extension"

[webhooks.privacy_compliance]
customer_deletion_url = "https://promopopup.vercel.app/webhooks"
customer_data_request_url = "https://promopopup.vercel.app/webhooks"
shop_deletion_url = "https://promopopup.vercel.app/webhooks"
